[workspace]
resolver = "2"
members = [
    "cardahoy-api",
    "cardahoy-crypto",
    "cardahoy-scanner",
    "cardahoy-utils",
]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
